name: Mirror and run GitLab CI

on: [push]

jobs:
  # svanboxel:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Mirror + trigger CI
  #     uses: SvanBoxel/gitlab-mirror-and-ci-action@master
  #     with:
  #       args: "https://gitlab.hzdr.de/j.fritz/github2gitlab_dummy.git"
  #     env:
  #       FORCE_PUSH: "true"
  #       GITLAB_HOSTNAME: "gitlab.hzdr.de"
  #       GITLAB_USERNAME: "j.fritz"
  #       GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
  #       GITLAB_PROJECT_ID: "6234"
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ubc_github2gitlab:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: pull github2gitlab
        uses: actions/checkout@v3
        with:
          repository: jakob-fritz/github2gitlab_action
          ref: master
          path: github2gitlab_action
      - name: check cloning
        run: |
          ls
      - name: check cloning
        run: |
          ls ./github2gitlab_action/
      - name: install github2gitlab
        run: |
          pip install ./github2gitlab_action
      - name: make mirror executable
        run: |
          chmod +x ./github2gitlab_action/bin/mirror.sh
          chmod +x ./github2gitlab_action/bin/getpasswd.sh
      # - name: get git info
      #   run: |
      #     git status
      - name: Mirror
        run: |
          ./github2gitlab_action/bin/mirror.sh
        env:
          GITLAB_USERNAME: "j.fritz"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_REPO_URL: "https://gitlab.hzdr.de/j.fritz/github2gitlab_dummy.git"
          FORCE_PUSH: "true"
      - name: Update Merge-Requests
        run: |
          github2gitlab \
            --gitlab-url "https://gitlab.hzdr.de" \
            --gitlab-token "${{ secrets.GITHUB_TOKEN }}" \
            --gitlab-repo "j.fritz/github2gitlab_dummy" \
            --gitlab-repo_id "6234" \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --github-repo jakob-fritz/Github2Gitlab_dummy \
            --ignore-closed
        env:
          GITLAB_USERNAME: "j.fritz"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_REPO_URL: "git@gitlab.hzdr.de/j.fritz/github2gitlab_dummy.git"
