name: Mirror and run GitLab CI

on: [push]

jobs:
  svanboxel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.hzdr.de/j.fritz/github2gitlab_dummy.git"
      env:
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.hzdr.de"
        GITLAB_USERNAME: "j.fritz"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "6234"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ubc_github2gitlab:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: install github2gitlab
        run: |
          pip install github2gitlab==1.5.5
      - name: Mirror + trigger CI
        run: |
          github2gitlab \
            --gitlab-url "https://gitlab.hzdr.de/" \
            --gitlab-token "${{ secrets.GITHUB_TOKEN }}" \
            --gitlab-repo "j.fritz/github2gitlab_dummy" \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --github-repo jakob-fritz/Github2Gitlab_dummy \
            --ignore-closed
