# SPDX-FileCopyrightText: 2022 Jakob Fritz <j.fritz@fz-juelich.de>
#
# SPDX-License-Identifier: MIT

name: Combined - Mirror and run GitLab CI

on: [push, pull_request_target]

jobs:
  github2lab:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror and get status
      uses: jakob-fritz/github2lab_action@make_action_work
      env:
        MODE: 'both' # Either 'mirror', 'get_status', or 'both'
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "codebase.helmholtz.cloud"
        GITLAB_PROJECT_ID: "6235"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
